# Generated by Django 5.2.4 on 2025-12-28 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='user email'),
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='user email')),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('history', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='core.uploadedimage')),
            ],
            options={
                'indexes': [models.Index(fields=['user_email'], name='core_chathi_user_em_69c172_idx'), models.Index(fields=['uploaded_image'], name='core_chathi_uploade_993738_idx')],
            },
        ),
    ]
