# Generated by Django 5.2.4 on 2025-12-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_uploadedimage_user_email_chathistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='user_email',
        ),
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
